spring:
  datasource:
    url: jdbc:mysql://mysqlserver-vhhh-2023.mysql.database.azure.com:3306/bancounion?useSSL=true
    username: azureuser
    password: 7G2%%3cTCKG1Dl0A
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


application:
  message: Configured by Azure Spring Apps
